stages:
  ['build', 'test']

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  SPRING_MAIL_HOST: mailhog
  SPRING_MAIL_PORT: 1025

cache:
  paths:
    - backend/.m2/repository
    - frontend/node_modules

build_backend:
  stage: 'build'
  image: maven:3.9.9-eclipse-temurin-21
  script:
    - cd backend
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - backend/target/*.jar

install-frontend:
  stage: 'build'
  image: node:20
  script:
    - cd frontend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - frontend/dist

backend-test:
  stage: 'test'
  image: maven:3.9.9-eclipse-temurin-21

  services:
    - name: mailhog/mailhog:latest
      alias: mailhog
  script:
    - cd backend
    - mvn test

  artifacts:
    when: always
    paths:
      - backend/target/surefire-reports

frontend-test:
  stage: 'test'
  image: node:20
  script:
    - cd frontend
    - npm ci
    - npm run test -- --run

