spring.application.name=SmartPay-BackEnd


# h2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# db config
spring.datasource.url=jdbc:h2:mem:smartpayDB
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JPA / hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.how-sql=true
spring.jpa.properties.hibernate.format_sql=true