spring.application.name=SmartPay-BackEnd


# h2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# db config
spring.datasource.url=jdbc:h2:mem:smartpayDB
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JPA / hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# spring security (default, to be removed later)
spring.security.user.name=admin
spring.security.user.password=admin

# frontend URL
app.frontend.url=http://localhost:5173

# email
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=noreply@smartpay.local
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

#actuator for dev
management.endpoints.web.exposure.include=health,info,metrics,env,beans,mappings,loggers
management.endpoint.health.show-details=always
management.metrics.enable.all=true

# jwt security (dev said it was fine to have a secret here for now)
jwt.secret=smartpay-demo-secret-key-1234567890-abcdefghij
jwt.expirationSeconds=3600

#jwt config related to session
# milliseconds
jwt.access.token.expiration=300000
jwt.refresh.token.expiration=900000

# Session Configuration
session.default.timeout.minutes=15

#Personal Information Encryption Secret Key
encryption.secret-key =MySuperSecretKey
